spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#queue name
rabbitmq:
  queue.name: leaningmq
  exchange.name: leaningmq_exchange
  routing.key: leaningmq_routing_key
